name: "In Principio"
description: "∞"
author: "Jxnblk"
url: "http://inprincip.io"

paginate: 20
permalink: /:title/

# UnComment once you have pygments installed. Used for code syntax highlighting.
pygments: true
